[changelog]
header = """# Changelog\n\n"""
body = """
## {{ tag }} - {{ timestamp | date(format="%Y-%m-%d") }}
{{#if groups}}
{{#each groups}}
### {{ title }}
{{#each commits}}
- {{ message | trim }}
{{/each}}

{{/each}}
{{else}}
- No notable changes.
{{/if}}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = "v[0-9].*"
protect_breaking_commits = true
