name: Prerelease to NuGet

on:
  pull_request:
    types: [closed]
    branches:
      - main

  workflow_dispatch:
    inputs:

      semver-build-prefix:
        description: "Prerelease prefix (preview, alpha, beta, rc)"
        type: choice
        options:
          - preview
          - alpha
          - beta
          - rc
        default: preview

      force-publish:
        description: "Force publish even if already tagged"
        type: boolean
        default: false

jobs:
  prerelease:
    name: Prerelease
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true)
    uses: vmelamed/vm2.DevOps/.github/workflows/_prerelease.yaml@5ec227717fab0a3f29e3e1a4caecc6b6306c61b9 # replace with main branch once stable
    permissions:
      contents: write
      packages: write # Required for GitHub Packages
    with:
      package-project: './vm2.TestUtilities.slnx'
      dotnet-version: ${{ vars.DOTNET_VERSION || '10.0.x' }}
      semver-build-prefix: ${{ inputs.semver-build-prefix || 'preview' }}
      force-publish: ${{ inputs.force-publish || false }}
      save_package_artifacts: true
      nuget-server: github # Publish to GitHub Packages
    secrets:
      NUGET_GITHUB_TOKEN: ${{ secrets.NUGET_GITHUB_TOKEN }}
