name: Release to NuGet

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Match v1.2.3
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+" # Match v1.2.3.4

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual release"
        required: true
        type: string

      force-publish:
        description: "Force publish"
        type: boolean
        default: false

jobs:
  log-trigger:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Log manual trigger reason
        run: |
          echo "::warning::Manual release triggered by ${{ github.actor }}"
          echo "::warning::Reason: ${{ inputs.reason }}"

  release:
    name: Stable Release
    needs: [log-trigger]
    if: always()
    uses: vmelamed/vm2.DevOps/.github/workflows/_release.yaml@a7dffe902fcdbab1a3c5e63c1841ced5108f8440 # replace with main branch once stable
    permissions:
      contents: write
      packages: write
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_GITHUB_KEY }}
    with:
      package-project: "./vm2.TestUtilities.slnx"
      dotnet-version: ${{ vars.DOTNET_VERSION || '10.0.x' }}
      force-publish: ${{ inputs.force-publish || false }}
      save_package_artifacts: true
      nuget-server: github
