name: Release to NuGet

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Match v1.2.3
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+" # Match v1.2.3.4

  workflow_dispatch:
    inputs:
      force-publish:
        description: "Force publish"
        type: boolean
        default: false

jobs:
  release:
    name: Stable Release
    uses: vmelamed/vm2.DevOps/.github/workflows/_release.yaml@5ec227717fab0a3f29e3e1a4caecc6b6306c61b9 # replace with main branch once stable
    secrets:
      NUGET_GITHUB_TOKEN: ${{ secrets.NUGET_GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: write # Required for GitHub Packages
    with:
      package-project: "./vm2.TestUtilities.slnx"
      dotnet-version: ${{ vars.DOTNET_VERSION || '10.0.x' }}
      force-publish: ${{ inputs.force-publish || false }}
      save_package_artifacts: true
      nuget-server: github # Publish to GitHub Packages
